# Generated by Django 4.2.6 on 2023-10-20 21:50

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='id',
            field=models.CharField(default=core.utils.generate_long_id, editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
