# Generated by Django 4.2.6 on 2023-10-21 14:19
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_eventmember_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.CharField(default=core.utils.generate_long_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('calendar', models.FileField(upload_to='calendar')),
            ],
        ),
    ]
