# Generated by Django 4.2.6 on 2023-10-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_time',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='min_time',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
