# Generated by Django 4.2.6 on 2023-10-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_max_time_event_min_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Your mom', max_length=255),
            preserve_default=False,
        ),
    ]
